version: '3'
services:
  parking-finder-api:
    container_name: parking-finder-api
    build: .
    ports:
      - "80:5009"
    image: registry.gitlab.com/parking-finder/parking-finder-api/park-finder-api:${TAG}
    environment:
      - REDIS_ADDRESS=redis:6379
    networks:
      - my-network
  redis:
    image: "redis:alpine"
    networks:
      - my-network

  parking-finder-cronjob:
    container_name: parking-finder-cronjob
    image: registry.gitlab.com/parking-finder/parking-finder-api/park-finder-api/cronjob:${TAG}
    ports:
      - 4200:4200
    command: ["python", "app.py"]
    restart: always
    network_mode: bridge

  parking-finder-demo:
    container_name: parking-finder-demo
    image: registry.gitlab.com/parking-finder/parking-finder-api/park-finder-api/demo:${TAG}
    ports:
      - 4500:4500
    command: ["python", "app.py"]
    restart: always
    network_mode: bridge

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

networks:
  my-network:
    driver: bridge




