# syntax=docker/dockerfile:1

FROM python:3.9-slim AS builder

WORKDIR /app

# Install necessary system libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY src /app/src
COPY requirements.txt ./
COPY .env ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./