version: '3'
services:
  parking-finder-process:
    container_name: parking-finder-process
    build: .
    ports:
      - "4800:4800"
    image: registry.gitlab.com/parking-finder/park-finder-process/park-finder-process:${TAG}
    networks:
      - my-network
  


networks:
  my-network:
    driver: bridge

